# Generated by Django 4.2.dev20220617091430 on 2025-02-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nbablogapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="users_followers", to="nbablogapp.user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="users_following", to="nbablogapp.user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="liked_posts",
            field=models.ManyToManyField(blank=True, to="nbablogapp.post"),
        ),
    ]
